export const LOGIN = "LOGIN";

export const REQUEST_AUTHENTICATION = "REQUEST_AUTHENTICATION";
export const AUTHENTICATION_REQUEST_SUCCESS = "AUTHENTICATION_REQUEST_SUCCESS";
export const AUTHENTICATION_REQUEST_FAIL = "AUTHENTICATION_REQUEST_FAIL ";

export const REQUEST_CREATE_JOB = "REQUEST_CREATE_JOB";
export const REQUEST_CREATE_JOB_SUCCESS = "REQUEST_CREATE_JOB_SUCCESS";
export const REQUEST_CREATE_JOB_FAIL = "REQUEST_CREATE_JOB_FAIL";

export const REQUEST_VIEW_JOB = "REQUEST_VIEW_JOB";
export const REQUEST_VIEW_SUCCESS = "REQUEST_VIEW_SUCCESS";
export const REQUEST_VIEW_FAIL = "REQUEST_VIEW_FAIL";

export const REQUEST_LIST_USERS = "REQUEST_VIEW_USERS";
export const REQUEST_USERS_SUCCESS = "REQUEST_USERS_SUCCESS";
export const REQUEST_USERS_FAIL = "REQUEST_USERS_FAIL";

export const REQUEST_UPDATE_USERS = "REQUEST_VIEW_USERS";
export const REQUEST_UPDATE_USERS_SUCCESS = "REQUEST_USERS_SUCCESS";
export const REQUEST_UPDATE_USERS_FAIL = "REQUEST_USERS_FAIL";

export const LOGOUT = "LOGOUT";
